import type { DealData } from "@/lib/deal-data";

const deal: DealData = {
  // ── Meta ─────────────────────────────────────────────────────
  slug: "third-point-sony",
  title: "Third Point vs. Sony — The Activism Campaign That Made $600M While Losing the Argument",
  subtitle: "Dan Loeb Activism · Sony Entertainment IPO Spinoff Demand · Japan Activism Barriers · Conglomerate Discount",
  category: "activism",
  industry: "Consumer Electronics & Entertainment",
  country: "Japan",
  announcedAt: "2013-05-14",
  closedAt: "2014-08-07",
  announcedDisplay: "May 2013",
  closedDisplay: "August 2014",
  readingMinutes: 9,
  tags: ["Third Point", "Sony", "Dan Loeb", "activism", "Sony Entertainment", "conglomerate discount", "Japan activism", "carve-out"],
  excerpt:
    "Dan Loeb's Third Point LLC built a 6.5% stake (~$1.1B) in Sony and demanded an IPO carve-out of Sony Entertainment. Sony's CEO and board refused outright. The demand failed — but the stock rose 70% during the campaign, generating ~$600M in profit. A masterclass in winning economically while losing strategically.",

  // ── Company Badges ───────────────────────────────────────────
  acquirer: { initials: "3P", bg: "bg-orange-600", label: "Third Point" },
  target:   { initials: "SNY", bg: "bg-gray-800", label: "Sony" },

  // ── Background ───────────────────────────────────────────────
  background: [
    "In 2013, Sony was a consumer electronics giant in deep distress. Once the world's premier consumer electronics brand, it had lost ground to Samsung and Apple across TVs, smartphones, and PCs — posting net losses for five straight years. Yet buried inside this struggling hardware company were two thriving businesses: Sony Music and Sony Pictures.",
    "Dan Loeb's Third Point LLC acquired a 6.5% stake in Sony (~$1.1B) in May 2013 and fired off a high-profile public letter. The core demand: spin off 15–20% of Sony Entertainment (music + film) through an IPO, separating its value from the electronics division's losses and unlocking hidden shareholder value.",
    "Sony CEO Kaz Hirai refused flatly. 'The synergy between entertainment and electronics is central to our strategy,' was the message. The board backed him. Japan's corporate structure — cross-shareholdings with main banks and stable institutional shareholders — acted as a structural firewall against activist pressure.",
    "Despite the failed demand, Sony's stock surged 70% during the campaign. Third Point sold most of its stake in August 2014, booking approximately $600M in profit. The structural change was blocked — but the trade was a success. Sony eventually proved Third Point right in 2021, renaming itself Sony Group Corporation and spinning off its electronics business on its own terms.",
  ],

  // ── Deal Summary ─────────────────────────────────────────────
  dealSummary: {
    dealValueDisplay: "Sony Market Cap ~¥1.8T",
    acquirerName: "Third Point LLC",
    targetName: "Sony Corporation",
    announcedDisplay: "May 2013",
    closedDisplay: "August 2014",
    country: "Japan",
  },

  // ── Executive Summary ────────────────────────────────────────
  executiveSummary: [
    "Third Point acquired 6.5% of Sony (~$1.1B) and demanded a 15–20% IPO carve-out of Sony Entertainment (music + film).",
    "Sony CEO Kaz Hirai and the board refused outright. Japan's cross-shareholding and main-bank structure acted as a structural defense against activist pressure.",
    "Sony's stock rose 70% during the campaign. Third Point exited in August 2014 with approximately $600M in profit.",
    "The core demand (Sony Entertainment IPO) failed. But Sony itself executed a structural reorganization in 2021 — rebranding as Sony Group Corporation and spinning off electronics.",
    "Key lesson: Japanese corporate activism works better through long-term ownership and indirect competitive pressure than public confrontation.",
  ],

  // ── Industry Overview ────────────────────────────────────────
  industryOverview: {
    body: "The Japanese conglomerate discount was the central thesis of Third Point's Sony campaign. Sony's three major business segments — electronics, entertainment, and financial services — were bundled under one legal entity, preventing the market from independently pricing each division. The electronics segment's recurring losses consumed the profits generated by entertainment and financial services, depressing Sony's overall valuation. Third Point's thesis was simple: separate the pieces and the sum-of-parts immediately becomes visible.",
    metrics: [
      { label: "Sony Electronics (FY2013)",      value: "Operating Loss", sub: "TV · Smartphone · PC" },
      { label: "Sony Entertainment Est. Value",  value: "$5–7B",         sub: "Third Point estimate (2013)" },
      { label: "Third Point Investment",          value: "~$1.1B",        sub: "6.5% stake" },
      { label: "Stock Return During Campaign",    value: "+70%",          sub: "May 2013 – Aug 2014" },
    ],
    subBody:
      "The streaming revolution was underway — Netflix's rise was making content IP more valuable than ever. Sony Pictures and Sony Music held durable moats: film libraries, music catalogues, artist relationships. But these assets were priced as part of a money-losing hardware company. Third Point's carve-out demand was essentially a bet that the market would eventually reprice these assets independently.",
    players: [
      { name: "Third Point LLC (Dan Loeb)",    role: "Activist hedge fund, 6.5% Sony stake" },
      { name: "Sony Management (Kaz Hirai)",   role: "Anti-separation; defended entertainment-electronics synergy" },
      { name: "Panasonic · Sharp",             role: "Japanese electronics peers, similarly distressed" },
      { name: "Netflix",                       role: "Streaming expansion driving content IP revaluation" },
    ],
  },

  // ── Company Overview ─────────────────────────────────────────
  companyOverview: {
    targetName: "Sony Corporation",
    body: "Sony Corporation was founded in 1946 and had grown into a global conglomerate spanning consumer electronics (TVs, smartphones, cameras, semiconductors), music (Sony Music Entertainment), film (Sony Pictures Entertainment), financial services (Sony Financial), and gaming (PlayStation). As of FY2013, the electronics segment had recorded net losses for five consecutive years, while entertainment and financial services remained consistently profitable. The divergence created a structural valuation gap that Third Point sought to exploit.",
    metrics: [
      { label: "Employees (FY2013)",          value: "~150,000",      sub: "Global consolidated" },
      { label: "Market Capitalization",       value: "~¥1.8T",        sub: "2013 basis" },
      { label: "Electronics Operating Profit", value: "Loss",         sub: "5 consecutive years of net loss" },
      { label: "Music & Film Operating Profit", value: "Profitable",  sub: "Sony Music + Sony Pictures" },
      { label: "ROE",                         value: "Negative",      sub: "Dragged down by electronics losses" },
      { label: "Business Segments",           value: "Electronics · Financial · Entertainment", sub: "3 core divisions" },
    ],
    financials: [
      { year: "FY2011", revenue: 7181, cogs: 5450, grossProfit: 1731, sga: 1690, operatingIncome: 41,  ebitda: 320 },
      { year: "FY2012", revenue: 6800, cogs: 5180, grossProfit: 1620, sga: 1610, operatingIncome: 10,  ebitda: 290 },
      { year: "FY2013", revenue: 7767, cogs: 5890, grossProfit: 1877, sga: 1780, operatingIncome: 97,  ebitda: 410 },
      { year: "FY2014", revenue: 8216, cogs: 6270, grossProfit: 1946, sga: 1850, operatingIncome: 96,  ebitda: 430 },
    ],
    financialsNote: "Unit: ¥B (billions of yen) | IFRS consolidated basis | Source: Sony Annual Report",
    financialsCurrency: "¥",
    financialsUnit: "B",
  },

  // ── Governance Overview ──────────────────────────────────────
  governanceOverview: {
    body: "Sony's governance challenges stemmed from its classic Japanese conglomerate structure. Electronics, entertainment, and financial services operated under a single legal entity, preventing independent market pricing of each division. The main-bank cross-shareholding structure created a bloc of stable institutional shareholders resistant to activist demands — a structural defense that Third Point ultimately could not overcome through public pressure alone.",
    shareholders: [
      {
        id: "third-point",
        label: "Third Point LLC",
        sub: "Dan Loeb activist fund",
        stake: "6.5%",
        stakePct: 6.5,
        type: "activist",
        alignment: "anti",
      },
      {
        id: "jp-institutional",
        label: "Japanese Institutional Investors (Banks & Insurers)",
        sub: "Main bank cross-shareholding bloc",
        stake: "25%",
        stakePct: 25,
        type: "institutional",
        alignment: "pro",
      },
      {
        id: "foreign-institutional",
        label: "Foreign Institutional Investors",
        sub: "Global pension funds & asset managers",
        stake: "30%",
        stakePct: 30,
        type: "institutional",
        alignment: "neutral",
      },
      {
        id: "public",
        label: "Retail & Minority Shareholders",
        sub: "Individual and small investors",
        stake: "38.5%",
        stakePct: 38.5,
        type: "public",
        alignment: "neutral",
      },
    ],
    board: {
      total: 12,
      independent: 4,
      affiliated: 8,
      note: "Only 4 of 12 directors were independent. Most independent directors had connections to the Japanese business establishment, providing limited structural support for activist demands.",
    },
    issues: [
      {
        title: "Conglomerate Discount",
        description: "Electronics segment losses offset entertainment and financial services profits, masking independent segment value from market pricing.",
        severity: "critical",
      },
      {
        title: "Japanese Cross-Shareholding Structure",
        description: "Reciprocal shareholding with main banks created a stable bloc of pro-management shareholders, structurally blocking activist influence.",
        severity: "high",
      },
      {
        title: "Board Independence",
        description: "Low ratio of genuinely independent directors. Board restructuring decisions were slow and resistant to external activist pressure.",
        severity: "high",
      },
      {
        title: "Lack of Strategic Focus",
        description: "Simultaneous operation of five business segments (electronics, music, film, financial services, gaming) diluted management focus and capital allocation efficiency.",
        severity: "medium",
      },
    ],
    demands: [
      {
        demand: "Sony Entertainment 15–20% IPO Carve-out",
        result: "lost",
        note: "Sony CEO and board refused outright. Management cited entertainment-electronics content synergy.",
      },
      {
        demand: "Shareholder Capital Efficiency Improvement",
        result: "partial",
        note: "Immediate demand failed. Sony executed its own restructuring in 2021, rebranding as Sony Group Corporation.",
      },
    ],
    stockImpact: {
      preCampaign: "¥1,050",
      peakDuringCampaign: "¥2,000",
      postCampaign: "¥1,750",
      note: "Sony's stock rose 70% during the Third Point campaign (May 2013–Aug 2014), reflecting a revaluation of its underappreciated assets despite the failed structural demand. Post-2021 Sony Group restructuring, the stock reached ¥12,000+.",
    },
  },

  // ── Deal Structure ───────────────────────────────────────────
  dealStructure: {
    body: "Third Point acquired Sony shares in the open market to build a 6.5% stake, then used its shareholder standing to issue a public letter demanding a partial IPO of Sony Entertainment (Sony Music + Sony Pictures). This was a carve-out demand — not an acquisition bid — aiming to unlock hidden value through partial listing of a subsidiary.",
    preOwnership: {
      nodes: [
        { id: "third-point",        label: "Third Point",            sub: "6.5% stake, demanding carve-out",         type: "acquirer" },
        { id: "sony-corp",          label: "Sony Corporation",       sub: "Electronics · Entertainment · Financial",  type: "target" },
        { id: "sony-entertainment", label: "Sony Entertainment",     sub: "Sony Music + Sony Pictures",               type: "entity" },
        { id: "sony-electronics",   label: "Sony Electronics",       sub: "TV · Smartphones · Cameras, loss-making",  type: "entity" },
        { id: "jp-banks",           label: "Japanese Main Banks",    sub: "Cross-shareholding defense bloc",          type: "fund" },
      ],
      edges: [
        { from: "third-point",        to: "sony-corp",          label: "6.5% (carve-out demand)" },
        { from: "sony-corp",          to: "sony-entertainment", label: "100% owned" },
        { from: "sony-corp",          to: "sony-electronics",   label: "100% owned" },
        { from: "jp-banks",           to: "sony-corp",          label: "Cross-shareholding defense" },
      ],
    },
    postOwnership: {
      nodes: [
        { id: "sony-corp",          label: "Sony Corporation",    sub: "Carve-out refused, structure unchanged",  type: "target" },
        { id: "sony-entertainment", label: "Sony Entertainment",  sub: "Retained internally (IPO abandoned)",     type: "entity" },
        { id: "third-point-exit",   label: "Third Point Exit",    sub: "Aug 2014 exit, ~$600M profit",            type: "fund" },
      ],
      edges: [
        { from: "sony-corp",        to: "sony-entertainment", label: "100% retained (no IPO)" },
        { from: "third-point-exit", to: "sony-corp",          label: "Stake sold, exited" },
      ],
    },
    keyTerms: [
      { label: "Third Point Stake",         value: "6.5%",                  accent: true },
      { label: "Investment Size",           value: "~$1.1B" },
      { label: "Carve-out Demand",          value: "Sony Entertainment 15–20% IPO" },
      { label: "CEO Response",             value: "Kaz Hirai — firm refusal",   accent: true },
      { label: "Stock Return (Campaign)",   value: "+70%" },
      { label: "Third Point Profit",        value: "~$600M",                accent: true },
    ],
  },

  // ── Advisors ─────────────────────────────────────────────────
  advisors: {
    body: "Third Point ran the campaign primarily through its internal investment team. Sony relied on its internal IR and legal departments, supported by its management team's direct public communications.",
    sides: [
      {
        side: "acquirer",
        sideLabel: "Third Point (Activist Side)",
        initials: "3P",
        bg: "bg-orange-600",
        advisors: [
          {
            firm: "Third Point LLC Internal Team",
            role: "Valuation & Campaign Strategy",
            roleType: "financial",
            note: "Independent valuation of Sony Entertainment ($5–7B). Public letter strategy and institutional investor engagement campaign.",
          },
        ],
      },
      {
        side: "target",
        sideLabel: "Sony (Defense Side)",
        initials: "SNY",
        bg: "bg-gray-800",
        advisors: [
          {
            firm: "Sony Internal IR & Legal Teams",
            role: "Activist Defense",
            roleType: "other",
            note: "CEO Kaz Hirai issued public refusal statements directly. Internal team developed synergy defense narrative for institutional investors.",
          },
        ],
      },
    ],
    disclaimer: "Note: Advisor information is based on public sources. Actual engagement terms may differ.",
  },

  // ── Valuation ────────────────────────────────────────────────
  valuation: {
    body: "Third Point's core valuation argument was that Sony Entertainment's standalone value ($5–7B) was receiving zero credit in Sony's overall market capitalization. The electronics division's persistent losses created a conglomerate discount that entirely masked the entertainment assets' worth.",
    rows: [
      { item: "Sony Entry Price",                     val: "¥1,050",        note: "May 2013 basis" },
      { item: "Campaign Peak Price",                  val: "¥2,000",        note: "2013–2014 high" },
      { item: "Third Point Exit Price",               val: "¥1,750–1,850",  note: "August 2014 basis" },
      { item: "Sony Entertainment Est. Value (3P)",   val: "$5–7B",         note: "Sony Music + Sony Pictures combined", accent: true },
      { item: "Stock Return During Campaign",         val: "+70%",          note: "vs. entry price",                     accent: true },
      { item: "Third Point Realized Profit",         val: "~$600M",        note: "August 2014 exit",                    accent: true },
    ],
    disclaimer: "Note: Stock prices and valuation figures are based on public data and estimates. Actual returns may differ.",
  },

  // ── Rationale ────────────────────────────────────────────────
  rationale: {
    buyer: {
      title: "Why Did Third Point Push for the Sony Entertainment Spinoff?",
      initials: "3P",
      bg: "bg-orange-600",
      points: [
        "Conglomerate discount elimination: Sony Entertainment's $5–7B standalone value was receiving zero market recognition inside the consolidated Sony entity.",
        "Immediate value unlock via partial IPO: A 15–20% Sony Entertainment listing would have crystallized billions in value for shareholders immediately.",
        "Shield entertainment from electronics drag: Structurally separating the profitable entertainment segment from the loss-making electronics division would stop the annual value destruction.",
        "Streaming era positioning: With Netflix's rise driving premium valuations for content IP, spinning off Sony Entertainment would allow it to be repriced as a pure-play streaming-era content company.",
      ],
    },
    seller: {
      title: "Why Did Sony Refuse?",
      initials: "SNY",
      bg: "bg-gray-800",
      points: [
        "Entertainment-electronics content synergy: Sony's integrated ecosystem strategy relied on exclusive content flowing from Sony Pictures and Sony Music to Sony TVs and smartphones.",
        "Sony brand integrity: The unified Sony brand spanning hardware, software, and content was seen as a strategic asset that would be diluted by separation.",
        "Japanese corporate culture's stability preference: Structural separation risked disrupting long-term relationships with employees, suppliers, and main-bank shareholders.",
        "Principled rejection of short-term capital: Sony's management refused to subordinate its long-term platform strategy to the exit-return calculus of an activist fund.",
      ],
    },
  },

  // ── Post-Deal Assessment ─────────────────────────────────────
  postDealAssessment: {
    asOfDate: "May 2026",
    body: "Third Point failed to win its core structural demand but succeeded spectacularly as a trade. A 70% stock return during the campaign translated to approximately $600M in realized profit. More tellingly, Sony itself proved Third Point's thesis correct in 2021 — rebranding as Sony Group Corporation and spinning off its electronics business on its own timeline.",
    overallVerdict: "Third Point: Economic Win. Structural Change: Sony Did It Itself.",
    positives: [
      "70% stock appreciation during the campaign — approximately $600M in realized profit for Third Point.",
      "Sony's undervaluation publicly surfaced — institutional investors re-evaluated the entertainment asset quality.",
      "Accelerated Sony's own long-term restructuring: the 2021 Sony Group rebranding and electronics spinoff followed the same logic Third Point articulated in 2013.",
    ],
    risks: [
      "Core demand (Sony Entertainment IPO carve-out) failed outright. A clear demonstration of the structural limits of Japanese corporate activism.",
      "Japan's main-bank cross-shareholding structure proved impenetrable to public confrontation tactics.",
      "Suggests that public pressure campaigns against Japanese corporates may backfire by strengthening management resolve — quiet engagement may be more effective.",
    ],
    editorNote:
      "Third Point vs. Sony shows what winning economics with a losing argument looks like. The structural demand failed — but the stock went up 70%. Sony eventually proved Third Point right in 2021, eight years later, by restructuring on its own terms. Activism planted the seed; patience harvested the crop.",
  },

  // ── Tombstone ───────────────────────────────────────────────
  tombstone: {
    acquirerInitials: "3P",
    acquirerBg: "bg-orange-600",
    targetInitials: "SNY",
    targetBg: "bg-gray-800",
    acquirerName: "Third Point LLC",
    targetName: "Sony Corporation",
    dealTitle: "Third Point's Activism Campaign Against Sony Corporation",
    dealSize: "Investment ~$1.1B",
    dealSizeUSD: "approx. USD 1.1 Billion",
    evEbitda: "N/A (Activism)",
    closeDate: "Aug 2014",
  },

  // ── Sources ──────────────────────────────────────────────────
  sources: [
    { id: 1, text: "Third Point LLC, Open Letter to Sony Shareholders (May 14, 2013)" },
    { id: 2, text: "Sony Corporation, Response Statement to Third Point (June 2013), Sony IR Press Release" },
    { id: 3, text: "Third Point LLC, Sony Stake Disposal Disclosure (August 2014)" },
    { id: 4, text: "Sony Corporation Annual Reports, FY2011–FY2014" },
    { id: 5, text: "Bloomberg, 'Third Point Returns About $600 Million on Sony Bet' (August 2014)" },
    { id: 6, text: "Sony Group Corporation, Corporate Restructuring Announcement (2021)" },
  ],

  // ── SEO ─────────────────────────────────────────────────────
  seo: {
    title: "Third Point vs. Sony — The Activism Campaign That Made $600M While Losing the Argument",
    description:
      "Complete analysis of Dan Loeb's Third Point activism campaign against Sony. Sony Entertainment IPO carve-out demand, Japan's activism barriers, 70% stock return. The demand failed, but the investment succeeded. A defining case in activist hedge fund strategy.",
    keywords: [
      "Third Point Sony",
      "Dan Loeb activism",
      "Sony Entertainment spinoff",
      "Japan corporate activism",
      "conglomerate discount",
      "Sony stock",
      "Sony governance",
      "activist hedge fund Japan",
      "Sony restructuring",
      "activist exit strategy",
    ],
  },

  // ── Concepts ─────────────────────────────────────────────────
  concepts: [
    {
      term: "Conglomerate Discount",
      description: "The phenomenon where a multi-division company's market capitalization trades below the sum of its independently valued parts. Sony's electronics losses masked the entertainment segments' true value.",
    },
    {
      term: "Carve-out",
      description: "A transaction where a parent company sells a minority stake in a subsidiary through an IPO while retaining majority ownership. Third Point's core demand was a 15–20% Sony Entertainment carve-out.",
    },
    {
      term: "Japanese Main-Bank Structure",
      description: "A system where Japanese companies maintain reciprocal shareholding arrangements with their primary lending banks, creating a bloc of stable shareholders resistant to activist demands.",
    },
    {
      term: "Subsidiary IPO (Partial Listing)",
      description: "Listing a subsidiary on a public exchange to crystallize its independent market value. Used by activists to unlock hidden value within diversified conglomerates.",
    },
    {
      term: "Entertainment Asset Valuation",
      description: "The process of valuing content IP, music catalogues, and film libraries. Post-streaming era, these assets command premium multiples as scarce, durable intellectual property.",
    },
    {
      term: "Activist Exit Strategy",
      description: "How activist funds realize returns regardless of whether structural demands are met — by holding through stock re-rating driven by the campaign's public attention. Third Point's Sony exit is the canonical example.",
    },
  ],

  // ── FAQ ─────────────────────────────────────────────────────
  faq: [
    {
      q: "Why did Third Point demand a Sony Entertainment spinoff?",
      a: "Sony's electronics division was posting annual losses that consumed the profits from its music and film businesses. Third Point valued Sony Entertainment (Sony Music + Sony Pictures) at $5–7B on a standalone basis — but this value received no credit inside the conglomerate's stock price. A 15–20% IPO would have crystallized that value immediately without full separation.",
    },
    {
      q: "Why did Sony refuse Third Point's demand?",
      a: "Sony CEO Kaz Hirai argued that content-hardware integration was central to Sony's strategy — Sony TVs and smartphones needed exclusive access to Sony Pictures and Sony Music content. Beyond strategy, Japan's corporate culture and cross-shareholding structure made the board resistant to externally-driven structural change.",
    },
    {
      q: "Why is corporate activism difficult in Japan?",
      a: "Japan's main-bank cross-shareholding system creates blocs of stable, pro-management shareholders that make it structurally difficult for activists to build majority-aligned voting blocs. Public pressure campaigns can also backfire by strengthening management resolve. Long-term ownership and quiet bilateral dialogue tend to be more effective tools in the Japanese market.",
    },
    {
      q: "How much did Third Point make on the Sony trade?",
      a: "Third Point acquired approximately 6.5% of Sony at around ¥1,050 per share (~$1.1B total) in May 2013. By August 2014, when it sold most of the position, Sony's stock had risen ~70% to approximately ¥1,750–1,850. Realized profit was estimated at approximately $600M.",
    },
    {
      q: "What eventually happened to Sony?",
      a: "In 2021, Sony rebranded as Sony Group Corporation and separated its electronics business into a distinct subsidiary called Sony Electronics. This is precisely the structural unbundling Third Point had advocated in 2013 — eight years earlier. Sony's stock subsequently rose to ¥12,000+ from ¥1,750 at the time of Third Point's exit.",
    },
    {
      q: "What is a conglomerate discount?",
      a: "A conglomerate discount occurs when a diversified company's market capitalization trades below the sum of its individually valued business units. Investors apply a discount to reflect complexity, cross-subsidization between profitable and unprofitable divisions, and perceived management distraction. Activist funds exploit this by demanding spinoffs or carve-outs to unlock the discount.",
    },
  ],
};

export default deal;
